using learning_ms.Web.Application.Common.DTOs.AiChatBot;
using learning_ms.Web.Domain.Entities.AiChatBot;
namespace learning_ms.Web.Application.Mappings.AiChatBotMapper;
using Riok.Mapperly.Abstractions;
[Mapper]
public partial class AiChatBotMapper
{
    [MapperIgnoreTarget(nameof(AiChatBot.Id))]
    [MapperIgnoreTarget(nameof(AiChatBot.UserId))]
    [MapperIgnoreTarget(nameof(AiChatBot.UserRole))]
    [MapperIgnoreTarget(nameof(AiChatBot.SessionId))]
    [MapperIgnoreTarget(nameof(AiChatBot.LastUserMessage))]
    [MapperIgnoreTarget(nameof(AiChatBot.LastBotResponse))]
    [MapperIgnoreTarget(nameof(AiChatBot.PromptTokens))]
    [MapperIgnoreTarget(nameof(AiChatBot.CompletionTokens))]
    [MapperIgnoreTarget(nameof(AiChatBot.EstimatedCost))]
    [MapperIgnoreTarget(nameof(AiChatBot.IsActive))]
    [MapperIgnoreTarget(nameof(AiChatBot.IsArchived))]
    [MapperIgnoreTarget(nameof(AiChatBot.IsPinned))]
    [MapperIgnoreTarget(nameof(AiChatBot.IsShared))]
    [MapperIgnoreTarget(nameof(AiChatBot.ContainsSensitiveContent))]
    [MapperIgnoreTarget(nameof(AiChatBot.FlaggedForReview))]
    [MapperIgnoreTarget(nameof(AiChatBot.ModerationReason))]
    [MapperIgnoreTarget(nameof(AiChatBot.UserRating))]
    [MapperIgnoreTarget(nameof(AiChatBot.UserFeedback))]
    [MapperIgnoreTarget(nameof(AiChatBot.StartedAt))]
    [MapperIgnoreTarget(nameof(AiChatBot.EndedAt))]
    [MapperIgnoreTarget(nameof(AiChatBot.LastMessageAt))]
    [MapperIgnoreTarget(nameof(AiChatBot.CreatedAt))]
    [MapperIgnoreTarget(nameof(AiChatBot.UpdatedAt))]
    [MapperIgnoreTarget(nameof(AiChatBot.CreatedBy))]
    [MapperIgnoreTarget(nameof(AiChatBot.UpdatedBy))]
    [MapperIgnoreSource(nameof(CreateAiChatBotRequestDto.Id))]
    [MapperIgnoreSource(nameof(CreateAiChatBotRequestDto.UserId))]
    [MapperIgnoreSource(nameof(CreateAiChatBotRequestDto.UserRole))]
    [MapperIgnoreSource(nameof(CreateAiChatBotRequestDto.SessionId))]
    [MapperIgnoreSource(nameof(CreateAiChatBotRequestDto.IsActive))]
    [MapperIgnoreSource(nameof(CreateAiChatBotRequestDto.StartedAt))]
    [MapperIgnoreSource(nameof(CreateAiChatBotRequestDto.LastMessageAt))]
    [MapperIgnoreSource(nameof(CreateAiChatBotRequestDto.CreatedAt))]
    [MapperIgnoreSource(nameof(CreateAiChatBotRequestDto.UpdatedAt))]
    [MapperIgnoreSource(nameof(CreateAiChatBotRequestDto.CreatedBy))]
    [MapperIgnoreSource(nameof(CreateAiChatBotRequestDto.UpdatedBy))]
    public partial AiChatBot ToEntity(CreateAiChatBotRequestDto dto);
    [MapperIgnoreSource(nameof(AiChatBot.UserRole))]
    [MapperIgnoreSource(nameof(AiChatBot.LastUserMessage))]
    [MapperIgnoreSource(nameof(AiChatBot.LastBotResponse))]
    [MapperIgnoreSource(nameof(AiChatBot.SystemPrompt))]
    [MapperIgnoreSource(nameof(AiChatBot.PromptTokens))]
    [MapperIgnoreSource(nameof(AiChatBot.CompletionTokens))]
    [MapperIgnoreSource(nameof(AiChatBot.EstimatedCost))]
    [MapperIgnoreSource(nameof(AiChatBot.IsArchived))]
    [MapperIgnoreSource(nameof(AiChatBot.IsPinned))]
    [MapperIgnoreSource(nameof(AiChatBot.IsShared))]
    [MapperIgnoreSource(nameof(AiChatBot.ContainsSensitiveContent))]
    [MapperIgnoreSource(nameof(AiChatBot.FlaggedForReview))]
    [MapperIgnoreSource(nameof(AiChatBot.ModerationReason))]
    [MapperIgnoreSource(nameof(AiChatBot.UserRating))]
    [MapperIgnoreSource(nameof(AiChatBot.UserFeedback))]
    [MapperIgnoreSource(nameof(AiChatBot.EndedAt))]
    [MapperIgnoreSource(nameof(AiChatBot.LastMessageAt))]
    [MapperIgnoreSource(nameof(AiChatBot.UpdatedAt))]
    [MapperIgnoreSource(nameof(AiChatBot.CreatedBy))]
    [MapperIgnoreSource(nameof(AiChatBot.UpdatedBy))]
    public partial CreateAiChatBotResponseDto ToResponseDto(AiChatBot entity);
}
