services:
  postgres:
    image: postgres:17-alpine
    container_name: learning_ms_postgres
    env_file:
      - .env
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - learning_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learning_ms_api
    env_file:
      - .env
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=${DATABASE_NAME};Username=${DATABASE_USER};Password=${DATABASE_PASSWORD}"
    ports:
      - "${API_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  learning_postgres_data: