using learning_ms.Web.Application.Common.DTOs.User;
using learning_ms.Web.Domain.Entities.User;
using Riok.Mapperly.Abstractions;
namespace learning_ms.Web.Application.Mappings.UserMapper;
[Mapper]
public partial class UserMapper
{
  [MapperIgnoreTarget(nameof(User.Id))]
  [MapperIgnoreTarget(nameof(User.Password))]        
  [MapperIgnoreTarget(nameof(User.IsActive))]
  [MapperIgnoreTarget(nameof(User.Role))]
  [MapperIgnoreTarget(nameof(User.OTPCode))]
  [MapperIgnoreTarget(nameof(User.ResendOTPCode))]
  [MapperIgnoreTarget(nameof(User.OTPExpirationDate))]
  [MapperIgnoreTarget(nameof(User.AccessToken))]
  [MapperIgnoreTarget(nameof(User.RefreshToken))]
  [MapperIgnoreTarget(nameof(User.RefreshTokenExpirationDate))]
  [MapperIgnoreTarget(nameof(User.MagicLinkToken))]
  [MapperIgnoreTarget(nameof(User.ResendMagicLinkToken))]
  [MapperIgnoreTarget(nameof(User.VerifyMagicLinkToken))]
  [MapperIgnoreTarget(nameof(User.ForgotPassword))]
  [MapperIgnoreTarget(nameof(User.ResetPassword))]
  [MapperIgnoreTarget(nameof(User.BlockUser))]
  [MapperIgnoreTarget(nameof(User.UnBlockUser))]
  [MapperIgnoreTarget(nameof(User.MagicLinkTokenExpirationDate))]
  [MapperIgnoreTarget(nameof(User.FirebaseUid))]
  [MapperIgnoreTarget(nameof(User.FirebaseProvider))]
  [MapperIgnoreTarget(nameof(User.FirebaseIdToken))]
  [MapperIgnoreTarget(nameof(User.FirebaseRefreshToken))]
  [MapperIgnoreTarget(nameof(User.IsFirebaseEmailVerified))]
  [MapperIgnoreTarget(nameof(User.PhoneNumber))]
  [MapperIgnoreTarget(nameof(User.IsPhoneNumberVerified))]
  [MapperIgnoreTarget(nameof(User.PhotoUrl))]
  [MapperIgnoreTarget(nameof(User.FirebaseDisplayName))]
  [MapperIgnoreTarget(nameof(User.FirebaseLastLoginAt))]
  [MapperIgnoreTarget(nameof(User.FirebaseCreatedAt))]
  [MapperIgnoreTarget(nameof(User.IsFirebaseDisabled))]
  [MapperIgnoreTarget(nameof(User.FirebaseTenantId))]
  [MapperIgnoreTarget(nameof(User.CreatedAt))]
  [MapperIgnoreTarget(nameof(User.UpdatedAt))]
  [MapperIgnoreSource(nameof(CreateRegisterUserRequestDto.Password))]
  [MapperIgnoreTarget(nameof(User.FailedLoginAttempts))] 
  public partial User ToEntity(CreateRegisterUserRequestDto dto);

  [MapperIgnoreSource(nameof(User.Id))]
  [MapperIgnoreSource(nameof(User.Password))]
  [MapperIgnoreSource(nameof(User.OTPCode))]
  [MapperIgnoreSource(nameof(User.ResendOTPCode))]
  [MapperIgnoreSource(nameof(User.OTPExpirationDate))]
  [MapperIgnoreSource(nameof(User.AccessToken))]
  [MapperIgnoreSource(nameof(User.RefreshToken))]
  [MapperIgnoreSource(nameof(User.RefreshTokenExpirationDate))]
  [MapperIgnoreSource(nameof(User.MagicLinkToken))]
  [MapperIgnoreSource(nameof(User.ResendMagicLinkToken))]
  [MapperIgnoreSource(nameof(User.VerifyMagicLinkToken))]
  [MapperIgnoreSource(nameof(User.ForgotPassword))]
  [MapperIgnoreSource(nameof(User.ResetPassword))]
  [MapperIgnoreSource(nameof(User.BlockUser))]
  [MapperIgnoreSource(nameof(User.UnBlockUser))]
  [MapperIgnoreSource(nameof(User.MagicLinkTokenExpirationDate))]
  [MapperIgnoreSource(nameof(User.FirebaseUid))]
  [MapperIgnoreSource(nameof(User.FirebaseProvider))]
  [MapperIgnoreSource(nameof(User.FirebaseIdToken))]
  [MapperIgnoreSource(nameof(User.FirebaseRefreshToken))]
  [MapperIgnoreSource(nameof(User.IsFirebaseEmailVerified))]
  [MapperIgnoreSource(nameof(User.PhoneNumber))]
  [MapperIgnoreSource(nameof(User.IsPhoneNumberVerified))]
  [MapperIgnoreSource(nameof(User.PhotoUrl))]
  [MapperIgnoreSource(nameof(User.FirebaseDisplayName))]
  [MapperIgnoreSource(nameof(User.FirebaseLastLoginAt))]
  [MapperIgnoreSource(nameof(User.FirebaseCreatedAt))]
  [MapperIgnoreSource(nameof(User.IsFirebaseDisabled))]
  [MapperIgnoreSource(nameof(User.FirebaseTenantId))]
  [MapperIgnoreSource(nameof(User.FailedLoginAttempts))] 
  public partial CreateUserLoginResponseDto ToLoginResponseDto(User entity);
}
