namespace learning_ms.Web.Infrastructure.ConfigurationExtensions.RoleSeedSettingsExtensions;
public sealed class RoleSeedSettingsExtensions
{
    public const string SectionName = "RoleEmailSettings";

    public string? SuperAdminEmail { get; set; }
    public string? SuperAdminPassword { get; set; }
    public string? HeadOfDepartmentEmail { get; set; }
    public string? HeadOfDepartmentPassword { get; set; }
    public string? AcademicDirectorEmail { get; set; }
    public string? AcademicDirectorPassword { get; set; }
    public string? VicePrincipalEmail { get; set; }
    public string? VicePrincipalPassword { get; set; }
    public string? RegistrarEmail { get; set; }
    public string? RegistrarPassword { get; set; }
    public string? BursarEmail { get; set; }
    public string? BursarPassword { get; set; }
    public string? AccountantEmail { get; set; }
    public string? AccountantPassword { get; set; }
    public string? FinanceManagerEmail { get; set; }
    public string? FinanceManagerPassword { get; set; }
    public string? HrManagerEmail { get; set; }
    public string? HrManagerPassword { get; set; }
    public string? HrOfficerEmail { get; set; }
    public string? HrOfficerPassword { get; set; }
    public string? PayrollOfficerEmail { get; set; }
    public string? PayrollOfficerPassword { get; set; }
    public string? AdmissionsOfficerEmail { get; set; }
    public string? AdmissionsOfficerPassword { get; set; }
    public string? ExamOfficerEmail { get; set; }
    public string? ExamOfficerPassword { get; set; }
    public string? LibrarianEmail { get; set; }
    public string? LibrarianPassword { get; set; }
    public string? AssistantLibrarianEmail { get; set; }
    public string? AssistantLibrarianPassword { get; set; }
    public string? LabManagerEmail { get; set; }
    public string? LabManagerPassword { get; set; }
    public string? LabTechnicianEmail { get; set; }
    public string? LabTechnicianPassword { get; set; }
    public string? IctManagerEmail { get; set; }
    public string? IctManagerPassword { get; set; }
    public string? ItSupportEmail { get; set; }
    public string? ItSupportPassword { get; set; }
    public string? SystemAdminEmail { get; set; }
    public string? SystemAdminPassword { get; set; }
    public string? NetworkAdminEmail { get; set; }
    public string? NetworkAdminPassword { get; set; }
    public string? SecurityOfficerEmail { get; set; }
    public string? SecurityOfficerPassword { get; set; }
    public string? ProcurementOfficerEmail { get; set; }
    public string? ProcurementOfficerPassword { get; set; }
    public string? StoreKeeperEmail { get; set; }
    public string? StoreKeeperPassword { get; set; }
    public string? HostelManagerEmail { get; set; }
    public string? HostelManagerPassword { get; set; }
    public string? HostelWardenEmail { get; set; }
    public string? HostelWardenPassword { get; set; }
    public string? TransportManagerEmail { get; set; }
    public string? TransportManagerPassword { get; set; }
    public string? DriverEmail { get; set; }
    public string? DriverPassword { get; set; }
    public string? NurseEmail { get; set; }
    public string? NursePassword { get; set; }
    public string? SchoolDoctorEmail { get; set; }
    public string? SchoolDoctorPassword { get; set; }
    public string? CounselorEmail { get; set; }
    public string? CounselorPassword { get; set; }
    public string? ReceptionistEmail { get; set; }
    public string? ReceptionistPassword { get; set; }
    public string? SecretaryEmail { get; set; }
    public string? SecretaryPassword { get; set; }
    public string? PublicRelationsOfficerEmail { get; set; }
    public string? PublicRelationsOfficerPassword { get; set; }
    public string? QualityAssuranceManagerEmail { get; set; }
    public string? QualityAssuranceManagerPassword { get; set; }
    public string? QualityAssuranceOfficerEmail { get; set; }
    public string? QualityAssuranceOfficerPassword { get; set; }
    public string? ComplianceOfficerEmail { get; set; }
    public string? ComplianceOfficerPassword { get; set; }
    public string? LegalOfficerEmail { get; set; }
    public string? LegalOfficerPassword { get; set; }
    public string? MarketingManagerEmail { get; set; }
    public string? MarketingManagerPassword { get; set; }
    public string? EventCoordinatorEmail { get; set; }
    public string? EventCoordinatorPassword { get; set; }
    public string? SportsDirectorEmail { get; set; }
    public string? SportsDirectorPassword { get; set; }
    public string? SportsCoachEmail { get; set; }
    public string? SportsCoachPassword { get; set; }
    public string? DeanOfStudiesEmail { get; set; }
    public string? DeanOfStudiesPassword { get; set; }
    public string? DisciplineMasterEmail { get; set; }
    public string? DisciplineMasterPassword { get; set; }
    public string? ClassCoordinatorEmail { get; set; }
    public string? ClassCoordinatorPassword { get; set; }
    public string? TimetableOfficerEmail { get; set; }
    public string? TimetableOfficerPassword { get; set; }
    public string? CurriculumManagerEmail { get; set; }
    public string? CurriculumManagerPassword { get; set; }
    public string? AlumniCoordinatorEmail { get; set; }
    public string? AlumniCoordinatorPassword { get; set; }
    public string? ResearchCoordinatorEmail { get; set; }
    public string? ResearchCoordinatorPassword { get; set; }
    public string? TrainingCoordinatorEmail { get; set; }
    public string? TrainingCoordinatorPassword { get; set; }
    public string? FacilitiesManagerEmail { get; set; }
    public string? FacilitiesManagerPassword { get; set; }
    public string? MaintenanceSupervisorEmail { get; set; }
    public string? MaintenanceSupervisorPassword { get; set; }
}
