// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using learning_ms.Web.Infrastructure.Persistence;

#nullable disable

namespace learning_ms.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721115138_AddStudentProfileUserIdAndPendingImageCount")]
    partial class AddStudentProfileUserIdAndPendingImageCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("learning_ms.Web.Domain.Entities.StudentProfile.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("academic_year");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateOnly>("AdmissionDate")
                        .HasColumnType("date")
                        .HasColumnName("admission_date");

                    b.Property<string>("AdmissionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("admission_number");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("Allergies")
                        .HasColumnType("text")
                        .HasColumnName("allergies");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("text")
                        .HasColumnName("blood_group");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrentClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_class");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emergency_contact_phone_number");

                    b.Property<string>("EmergencyContactRelationship")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emergency_contact_relationship");

                    b.Property<string>("FatherFullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("father_full_name");

                    b.Property<string>("FatherOccupation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("father_occupation");

                    b.Property<string>("FatherPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("father_phone_number");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("GuardianEmail")
                        .HasColumnType("text")
                        .HasColumnName("guardian_email");

                    b.Property<string>("GuardianFullName")
                        .HasColumnType("text")
                        .HasColumnName("guardian_full_name");

                    b.Property<string>("GuardianPhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("guardian_phone_number");

                    b.Property<string>("GuardianRelationship")
                        .HasColumnType("text")
                        .HasColumnName("guardian_relationship");

                    b.PrimitiveCollection<List<string>>("Hobbies")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("hobbies");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsGraduated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_graduated");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MedicalConditions")
                        .HasColumnType("text")
                        .HasColumnName("medical_conditions");

                    b.Property<string>("Medications")
                        .HasColumnType("text")
                        .HasColumnName("medications");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("MotherFullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mother_full_name");

                    b.Property<string>("MotherOccupation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mother_occupation");

                    b.Property<string>("MotherPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mother_phone_number");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<int>("PendingImageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("pending_image_count");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("place_of_birth");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.PrimitiveCollection<List<string>>("ProfilePictureUrl")
                        .HasColumnType("text[]")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("Religion")
                        .HasColumnType("text")
                        .HasColumnName("religion");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_student_profiles");

                    b.HasIndex("AdmissionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_student_profiles_admission_number");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_student_profiles_user_id");

                    b.ToTable("student_profiles", (string)null);
                });

            modelBuilder.Entity("learning_ms.Web.Domain.Entities.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("access_token");

                    b.Property<bool>("BlockUser")
                        .HasColumnType("boolean")
                        .HasColumnName("block_user");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<DateTime?>("FirebaseCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("firebase_created_at");

                    b.Property<string>("FirebaseDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("firebase_display_name");

                    b.Property<string>("FirebaseIdToken")
                        .HasColumnType("text")
                        .HasColumnName("firebase_id_token");

                    b.Property<DateTime?>("FirebaseLastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("firebase_last_login_at");

                    b.Property<string>("FirebaseProvider")
                        .HasColumnType("text")
                        .HasColumnName("firebase_provider");

                    b.Property<string>("FirebaseRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("firebase_refresh_token");

                    b.Property<string>("FirebaseTenantId")
                        .HasColumnType("text")
                        .HasColumnName("firebase_tenant_id");

                    b.Property<string>("FirebaseUid")
                        .HasColumnType("text")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("ForgotPassword")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("forgot_password");

                    b.Property<DateTime>("ForgotPasswordExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("forgot_password_expiration_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFirebaseDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_firebase_disabled");

                    b.Property<bool>("IsFirebaseEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_firebase_email_verified");

                    b.Property<bool>("IsPhoneNumberVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_phone_number_verified");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MagicLinkToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("magic_link_token");

                    b.Property<DateTime>("MagicLinkTokenExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("magic_link_token_expiration_date");

                    b.Property<string>("OTPCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("otp_code");

                    b.Property<DateTime>("OTPExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_expiration_date");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime>("RefreshTokenExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiration_date");

                    b.Property<string>("ResendMagicLinkToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resend_magic_link_token");

                    b.Property<string>("ResendOTPCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("resend_otp_code");

                    b.Property<string>("ResetPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reset_password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<bool>("UnBlockUser")
                        .HasColumnType("boolean")
                        .HasColumnName("un_block_user");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerifyMagicLinkToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verify_magic_link_token");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
