// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using learning_ms.Web.Infrastructure.Persistence;

#nullable disable

namespace learning_ms.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("learning_ms.Web.Domain.Entities.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("access_token");

                    b.Property<bool>("BlockUser")
                        .HasColumnType("boolean")
                        .HasColumnName("block_user");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<DateTime?>("FirebaseCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("firebase_created_at");

                    b.Property<string>("FirebaseDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("firebase_display_name");

                    b.Property<string>("FirebaseIdToken")
                        .HasColumnType("text")
                        .HasColumnName("firebase_id_token");

                    b.Property<DateTime?>("FirebaseLastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("firebase_last_login_at");

                    b.Property<string>("FirebaseProvider")
                        .HasColumnType("text")
                        .HasColumnName("firebase_provider");

                    b.Property<string>("FirebaseRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("firebase_refresh_token");

                    b.Property<string>("FirebaseTenantId")
                        .HasColumnType("text")
                        .HasColumnName("firebase_tenant_id");

                    b.Property<string>("FirebaseUid")
                        .HasColumnType("text")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("ForgotPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forgot_password");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFirebaseDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_firebase_disabled");

                    b.Property<bool>("IsFirebaseEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_firebase_email_verified");

                    b.Property<bool>("IsPhoneNumberVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_phone_number_verified");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MagicLinkToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("magic_link_token");

                    b.Property<DateTime>("MagicLinkTokenExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("magic_link_token_expiration_date");

                    b.Property<string>("OTPCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("otp_code");

                    b.Property<DateTime>("OTPExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_expiration_date");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime>("RefreshTokenExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiration_date");

                    b.Property<string>("ResendMagicLinkToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resend_magic_link_token");

                    b.Property<string>("ResendOTPCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("resend_otp_code");

                    b.Property<string>("ResetPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reset_password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<bool>("UnBlockUser")
                        .HasColumnType("boolean")
                        .HasColumnName("un_block_user");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerifyMagicLinkToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verify_magic_link_token");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
